// Generated by CoffeeScript 1.4.0
(function() {
  var TaskkAPI;

  TaskkAPI = (function() {
    var auth, domain;

    domain = "https://api.taskk.it/v1/";

    auth = "";

    function TaskkAPI(token) {
      this.token = token;
      if (this.token) {
        auth = "?token=" + this.token;
      }
    }

    TaskkAPI.prototype.ping = function() {
      return $.get(domain + "auth/ping/" + auth);
    };

    TaskkAPI.prototype.get_lists = function() {
      return $.get(domain + "lists/" + auth);
    };

    TaskkAPI.prototype.get_tasks = function() {
      return $.get(domain + "tasks/" + auth);
    };

    TaskkAPI.prototype.get_task = function(id) {
      return $.get(domain + "tasks/" + id(+"/" + auth));
    };

    TaskkAPI.prototype.get_list = function(id) {
      return $.get(domain + "lists/" + id(+"/" + auth));
    };

    TaskkAPI.prototype.create_task = function(title, estimate, list_id) {
      return $.post(domain + "/tasks?", {
        title: title,
        estimate: estimate,
        list_id: list_id
      });
    };

    TaskkAPI.prototype.create_list = function(title, color) {
      return $.post(domain + "/lists?", {
        title: title,
        color: color
      });
    };

    return TaskkAPI;

  })();

  window.TaskkAPI = TaskkAPI;

}).call(this);
